### ISSUE TITLE
Writing string to characteristic?

### ISSUE THREAD

**Issue by Zander-M** [ITPNYU/p5.ble.js#11]
Hi, I'm wondering if you could provide a function to write a string to a characteristic? On line 104 you use the Uint8Array.of() function to parse the input value, in that case we can't write a string to a characteristic. Perhaps it can be changed to something like:

```javascript
const bufferToSend = new Uint8Array(toUTF8Array(inputValue));
```

so we can send value to the device? If it's a design choice, could you please let me know the reason for this? Thank you!

**Comment by ragrag** [comment]
Faced this issue as well and used 
```js
const bufferToSend = new TextEncoder("utf-8").encode(inputValue);
```

**Comment by yining1023** [comment]
Hi @Zander-M and @ragrag, thank you so much for your suggestions!

I updated the library to support writing strings from p5 sketch to Arduino. You can use p5.ble.js@0.0.7 to send string to Arduino:
```
<script src="https://unpkg.com/p5ble@0.0.7/dist/p5.ble.js" type="text/javascript"></script>
```

On the Arduino side, you might need to add this line to read the string: https://github.com/ITPNYU/p5.ble.js/blob/9de8a6b3e8153af9538e454fa436af23f7f4716c/examples/writeOneChar/arduino-sketches/write-one-char-ArduinoBLE/write-one-char-ArduinoBLE.ino#L70

Here is a demo video about how to send strings to Arduino: https://www.loom.com/share/7a179dea008c420dace27900baa9c444
Here are the [p5 sketch](https://editor.p5js.org/yining/sketches/Pm_NgW3J0) and the [Arduino code](https://github.com/ITPNYU/p5.ble.js/blob/master/examples/writeOneChar/arduino-sketches/write-one-char-ArduinoBLE/write-one-char-ArduinoBLE.ino) used in the demo video.


Thank you both for using p5.ble.js and please let us know if you have other feedback!

**Comment by ragrag** [comment]
@yining1023 
Thank you so much for that!

**Comment by Zander-M** [comment]
Thank you so much! This helps a lot! <3
