### ISSUE TITLE
Start Stop Notifications example on Arduino 101 doesn't work

### ISSUE THREAD

**Issue by yining1023** [ITPNYU/p5.ble.js#3]
I noticed that the "Start Stop Notifications example" with Arduino 101 doesn't work. it threw out the following error.
<img width="500" alt="Screen Shot 2019-08-04 at 2 56 39 PM" src="https://user-images.githubusercontent.com/8662372/62428284-f36bf400-b6cd-11e9-8ec8-8ccc1bac7a46.png">

I also tested the Notification example with Web BLE(on macOS) on Arduino 101, it also doesn't work, the error is: GATT Error, not supported:
<img width="500" alt="Screen Shot 2019-08-04 at 3 34 21 PM" src="https://user-images.githubusercontent.com/8662372/62428285-f535b780-b6cd-11e9-87f8-dee0a4445670.png">

This example was working fine a few months ago, I wonder what changed. I also found this discussion in the google group: https://groups.google.com/a/chromium.org/forum/#!topic/web-bluetooth/TlHnA3hTksw.

Maybe it's still working fine on other devices? @tigoe and @ZhuJingwen

**Comment by tigoe** [comment]
Works fine on the Nano 33 IoT.

Since the Arduino 101 is discontinued, I wouldn't worry about it too much if it's only on that device.  But worth testing with others to confirm.
