### ISSUE TITLE
float64 type doesn't work

### ISSUE THREAD

**Issue by tigoe** [ITPNYU/p5.ble.js#4]
Calling for .read() or .startNotifications() using 'float64' as the data type causes a sketch to fail.

Sample:

````
myBLE.startNotifications(characteristic, myHandler, 'float64');
````

error:

crashes on line 40 of p5.ble.js

**Comment by yining1023** [comment]
Thank you for filing the issue! I’ll look into it this week.

**Comment by tigoe** [comment]
Update: by adding the littleEndian flag on getFloat32(), the problem goes away. So I'd suggest adding in an option to use that flag for notifications, and the problem will be generally solvable.

**Comment by tigoe** [comment]
https://github.com/ITPNYU/physcomp/tree/master/Labs/LabIMUs/Nano33MadgwickBLE
and 
https://github.com/ITPNYU/physcomp/tree/master/Labs/LabIMUs/MadgwickVisualizerBLE
with a modified p5.ble.min.js show the example working. Use the non-modified p5.ble.min.js to see the issue.

**Comment by yining1023** [comment]
Hi @tigoe, I published a new version of [p5.ble.js 0.0.5](https://unpkg.com/p5ble@0.0.5/dist/p5.ble.js) that fixes this issue.

Now it reads data in little-Endian by default, so the following code will be working:
```
myBLE.startNotifications(characteristic, myHandler, 'float64');
```
And if people would like to read data in big-endian format, they can pass `float64-bigEndian` or `float32-bigEndian`.
```
myBLE.startNotifications(characteristic, myHandler, 'float64-bigEndian');
```

`myBLE.read` works the same as `myBLE.startNotifications`. I added a note to the [website](https://itpnyu.github.io/p5ble-website/docs/api#a-note-about-datatype-parameter-1).

Please let me know if it works for you. :)

**Comment by tigoe** [comment]
Works great, thanks @yining1023 I updated [this example](https://github.com/ITPNYU/physcomp/tree/master/Labs/LabIMUs) for both the Nano 33 IoT and BLE Sense as well, and it works pretty well.

**Comment by yining1023** [comment]
Yay! Thank you for testing it! ❤️
